server {
    listen 80;

    #/usr/share/nginx/html/management/index.html 파일을 찾아서 반환
    location = /management {
        root /usr/share/nginx/html; 
        try_files /management/index.html =404; # /management/index.html 파일이 존재하면 반환, 없으면 404 에러 반환
    }

    location = /management/ {
        root /usr/share/nginx/html;
        try_files /management/index.html =404; # /usr/share/nginx/html/management/index.html 파일을 찾아서 반환
    }

    location /management/ { # /management/로 시작하는 모든 요청에 대해 fastapi-service:8000으로 프록시 패스
        proxy_pass http://fastapi-service:8000/; # 이때 proxy_pass 끝에 /가 있으면, nginx가 /management/ 부분을 잘라내고 전달함!
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        proxy_pass http://fastapi-service:8000/health; # /health 경로로 들어오는 요청을 http://fastapi-service:8000/health로 프록시 패스
        proxy_set_header Host $host;
    }

    location /board {
    proxy_pass http://10.10.111.117:30080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
}