server {
    listen 80;

    location /management/static/ {
        root /usr/share/nginx/html;
    }

    location = /management {
        root /usr/share/nginx/html;
        try_files /management/index.html =404;
        #  → /usr/share/nginx/html/management/index.html 파일 반환 (HTML 화면)
    }

    location = /management/ {
        root /usr/share/nginx/html;
        try_files /management/index.html =404;
        # → 동일하게 index.html 반환 (HTML 화면)
    }

    location /management/ {
        proxy_pass http://fastapi-service:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        # → fastapi로 전달
        # 예: /management/members/ → fastapi:8000/members/
        # 예: /management/health  → fastapi:8000/health
    }
}